Transform: AWS::Serverless-2016-10-31
Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs12.x
      CodeUri: .
      Handler: index.handler
  Macro:
    Type: AWS::CloudFormation::Macro
    Properties:
      Name: SGIngressPorts
      FunctionName: !GetAtt Function.Arn